### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by GuardZ** [mdolab/cgnsutilities#26]
## Description
Running cgnsutilities with extract function will trigger the following:
`ValueError: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead`

This is probably introduced in new NumPy version from v1.4.0.

Someone may have interested in this [link](https://blog.apotelesm.info/2020/05/numpy-surprise-non-string-object.html).

**Comment by nwu63** [comment]
What version of numpy are you running? I haven't seen this error before.

**Comment by eirikurj** [comment]
Also can you comment on what version of python you are using.

**Comment by GuardZ** [comment]
Thanks for the reply. Here is my software list:
GCC-7.1.0
CMAKE-3.16.0
PYTHON-3.8.5
NumPy-1.18.5
SciPy-1.4.1

And about this issue, after I replace all the string <flatten('1')> with <flatten('F')>, this error will disappear.

**Comment by nwu63** [comment]
I just tried this and I'm able to reproduce the error. Would you mind submitting a PR for this @GuardZ?

**Comment by GuardZ** [comment]
Yeah. I will have a try.
