### ISSUE TITLE
Rename modes to use camelCase

### ISSUE THREAD

**Issue by nwu63** [mdolab/cgnsutilities#37]
# Description
Some modes use camelCase when others don't. To improve readability, we should change everything to camelCase. This will however break backwards compatibility, and if we want, we could cast everything to lower when comparing. But I am also fine with breaking backwards compatibility as long as we state it clearly in release notes.

**Comment by eirikurj** [comment]
I agree we should unify the options to be camelCase. 
For backwards compatibility, in general its not a big deal for this tool, but we can also consider to just include both options, e.g., `--overwritebc` and `--overwriteBC`.
