### ISSUE TITLE
Add sphinx documentation

### ISSUE THREAD

**Issue by nwu63** [mdolab/cgnsutilities#40]
# Description
Since this tool is actually somewhat complex, we may want to have a documentation site. This would include both auto-generated documentation (via `autoprogram` or equivalent), as well as some additional information for some file formats expected by the CLI tool (that don't fit into the help string). Some diagrams etc. may also be helpful.

Note that these Sphinx extensions that parse `argparser` are somewhat finicky, so #39 will be related to this effort.

**Comment by sseraj** [comment]
Possibly a duplicate of #14?

**Comment by nwu63** [comment]
Yep good point.
